id: PF5C949F7
initial_creation_type: ocr
source_metadata:
  volumes:
    cbe8fc2682b140a9941888a3b4689529:
      base_file: v014.txt
      image_group_id: I1PD95859
      title: རྡོ་རྗེ་ནག་པོ་ཆེན་པོའི་བསྟོད་པ་བརྒྱད་པ།
      total_pages: 1856
      volume_number: 14
